# Classifying

In [1]:
import keras
import sklearn.model_selection
import numpy as np
import pandas as pd

2023-01-14 02:46:30.955208: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-14 02:46:31.047057: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-01-14 02:46:31.047069: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-01-14 02:46:31.431107: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-

In [2]:
import utils.json_utils as jsu

### Load Inputs & Labels

In [3]:
X = np.array(jsu.read_json("10_X_subjects_black_clover.json"))
Y = np.array(jsu.read_json("10_Y_tokens_black_clover.json"))

### Separate into Train & Validation

In [4]:
#x_train, x_valid, y_train, y_valid = sklearn.model_selection.train_test_split(X, Y, test_size=0.3, random_state=0)
x_train, x_valid, y_train, y_valid = X, X, Y, Y

### Model

In [5]:
callback_early_stopping = keras.callbacks.EarlyStopping(monitor='val_loss', patience=10, verbose=0, mode='auto')

In [6]:

model = keras.models.Sequential()
model.add(keras.Input(shape=x_train.shape[1]))
"""
model.add(keras.layers.core.Dense(Y.shape[1]))
model.add(keras.layers.LeakyReLU(alpha=0.3))
model.add(keras.layers.core.Dense(Y.shape[1]))
model.add(keras.layers.LeakyReLU(alpha=0.3))
model.add(keras.layers.core.Dense(Y.shape[1]))
model.add(keras.layers.LeakyReLU(alpha=0.3))
model.add(keras.layers.core.Dense(Y.shape[1]))
model.add(keras.layers.LeakyReLU(alpha=0.3))
"""
model.add(keras.layers.core.Dense(Y.shape[1]))
model.add(keras.layers.LeakyReLU(alpha=0.3))
model.add(keras.layers.core.Dense(Y.shape[1]))
model.add(keras.layers.LeakyReLU(alpha=0.3))
model.add(keras.layers.core.Dense(Y.shape[1]))
model.add(keras.layers.LeakyReLU(alpha=0.3))
model.add(keras.layers.core.Dense(Y.shape[1]))
model.add(keras.layers.LeakyReLU(alpha=0.3))
model.add(keras.layers.core.Dense(Y.shape[1], activation='sigmoid'))
model.compile(loss="categorical_crossentropy", optimizer="adadelta",metrics=["accuracy"])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3528)              162288    
                                                                 
 leaky_re_lu (LeakyReLU)     (None, 3528)              0         
                                                                 
 dense_1 (Dense)             (None, 3528)              12450312  
                                                                 
 leaky_re_lu_1 (LeakyReLU)   (None, 3528)              0         
                                                                 
 dense_2 (Dense)             (None, 3528)              12450312  
                                                                 
 leaky_re_lu_2 (LeakyReLU)   (None, 3528)              0         
                                                                 
 dense_3 (Dense)             (None, 3528)              1

2023-01-14 02:46:33.965830: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-01-14 02:46:33.965854: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2023-01-14 02:46:33.965871: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Homura): /proc/driver/nvidia/version does not exist
2023-01-14 02:46:33.966121: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [7]:
"""
model = keras.models.Sequential()
model.add(keras.Input(shape=x_train.shape[1]))

model.add(keras.layers.core.Dense(Y.shape[1], activation='sigmoid'))
model.add(keras.layers.core.Dense(Y.shape[1], activation='sigmoid'))
model.add(keras.layers.core.Dense(Y.shape[1], activation='sigmoid'))
model.add(keras.layers.core.Dense(Y.shape[1], activation='sigmoid'))
model.add(keras.layers.core.Dense(Y.shape[1], activation='sigmoid'))

model.add(keras.layers.core.Dense(Y.shape[1], activation='sigmoid'))
model.add(keras.layers.core.Dense(Y.shape[1], activation='sigmoid'))
model.add(keras.layers.core.Dense(Y.shape[1], activation='sigmoid'))
model.add(keras.layers.core.Dense(Y.shape[1], activation='softmax'))
model.compile(loss="categorical_crossentropy", optimizer="adadelta",metrics=["accuracy"])
print(model.summary())
"""

'\nmodel = keras.models.Sequential()\nmodel.add(keras.Input(shape=x_train.shape[1]))\n\nmodel.add(keras.layers.core.Dense(Y.shape[1], activation=\'sigmoid\'))\nmodel.add(keras.layers.core.Dense(Y.shape[1], activation=\'sigmoid\'))\nmodel.add(keras.layers.core.Dense(Y.shape[1], activation=\'sigmoid\'))\nmodel.add(keras.layers.core.Dense(Y.shape[1], activation=\'sigmoid\'))\nmodel.add(keras.layers.core.Dense(Y.shape[1], activation=\'sigmoid\'))\n\nmodel.add(keras.layers.core.Dense(Y.shape[1], activation=\'sigmoid\'))\nmodel.add(keras.layers.core.Dense(Y.shape[1], activation=\'sigmoid\'))\nmodel.add(keras.layers.core.Dense(Y.shape[1], activation=\'sigmoid\'))\nmodel.add(keras.layers.core.Dense(Y.shape[1], activation=\'softmax\'))\nmodel.compile(loss="categorical_crossentropy", optimizer="adadelta",metrics=["accuracy"])\nprint(model.summary())\n'

In [8]:
model.fit(x_train, y_train, batch_size=1, epochs=10, validation_data=(x_valid, y_valid), verbose=1, callbacks=[callback_early_stopping])

Epoch 1/10
5989/5989 [==============================] - 2873s 480ms/step - loss: 80.5468 - accuracy: 0.0000e+00 - val_loss: 77.7487 - val_accuracy: 0.0000e+00
Epoch 2/10
5989/5989 [==============================] - 2868s 479ms/step - loss: 109.9758 - accuracy: 0.0000e+00 - val_loss: 197.1416 - val_accuracy: 0.0000e+00
Epoch 3/10
5989/5989 [==============================] - 2880s 481ms/step - loss: 688.1834 - accuracy: 0.0000e+00 - val_loss: 1589.5398 - val_accuracy: 0.0000e+00
Epoch 4/10
5989/5989 [==============================] - 2866s 479ms/step - loss: 4344.6152 - accuracy: 0.0000e+00 - val_loss: 8766.3623 - val_accuracy: 0.0000e+00
Epoch 5/10
5989/5989 [==============================] - 2869s 479ms/step - loss: 19238.8223 - accuracy: 1.6697e-04 - val_loss: 34519.3438 - val_accuracy: 8.3486e-04
Epoch 6/10
5989/5989 [==============================] - 2859s 477ms/step - loss: 64940.8398 - accuracy: 0.0000e+00 - val_loss: 107012.1562 - val_accuracy: 1.6697e-04
Epoch 7/10
5989/5989 [==

In [9]:
character2index = jsu.read_json("10_character2index_black_clover.json")
index2character = jsu.read_json("10_index2character_black_clover.json")

In [10]:
token2index = jsu.read_json("10_token2index_black_clover.json")
index2token = jsu.read_json("10_index2token_black_clover.json")

In [25]:
hot_encoded_yuno = np.zeros((1, len(character2index)))
hot_encoded_yuno[0][character2index['Yuno']] = 1

yuno = model.predict(hot_encoded_yuno)

1/1 [==============================] - 0s 24ms/step


In [26]:
top_tokens_indexes = np.argpartition(yuno[0], -20)[-20:]
top_tokens_indexes

array([1549, 1579, 1515, 1540, 1539, 1538, 1537, 1536, 1534, 1532, 1529,
       1528, 1527, 1526, 1523, 1522, 1521, 1519, 1516, 3527])

In [27]:
for token_index in top_tokens_indexes:
    print(yuno[0][token_index], '\t', index2token[str(token_index)])

1.0 	 pledge
1.0 	 baron
1.0 	 little
1.0 	 beach
1.0 	 absorb
1.0 	 singing
1.0 	 dante
1.0 	 locate
1.0 	 key
1.0 	 trinity
1.0 	 restraining
1.0 	 essential
1.0 	 fighting
1.0 	 numbing
1.0 	 Grey
1.0 	 explosive
1.0 	 advise
1.0 	 battle
1.0 	 spade
1.0 	 notice


In [22]:
np.where(yuno == np.max(yuno))

(array([0, 0, 0, ..., 0, 0, 0]),
 array([   0,    7,    8, ..., 3525, 3526, 3527]))

In [23]:
index2token['1323']

'go'

In [1]:
yuno

NameError: name 'yuno' is not defined