# Classifying

In [1]:
import keras
import sklearn.model_selection
import numpy as np
import pandas as pd

2023-01-15 02:02:58.247907: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-15 02:02:58.441833: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-01-15 02:02:58.441844: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-01-15 02:02:59.042471: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-

In [2]:
import utils.json_utils as jsu

### Load Inputs & Labels

In [3]:
X = np.array(jsu.read_json("10_X_subjects_black_clover.json"))
Y = np.array(jsu.read_json("10_Y_tokens_black_clover.json"))

### Separate into Train & Validation

In [4]:
#x_train, x_valid, y_train, y_valid = sklearn.model_selection.train_test_split(X, Y, test_size=0.3, random_state=0)
x_train, x_valid, y_train, y_valid = X, X, Y, Y

### Model

In [5]:
callback_early_stopping = keras.callbacks.EarlyStopping(monitor='val_loss', patience=10, verbose=0, mode='auto')

In [6]:

model = keras.models.Sequential()
model.add(keras.Input(shape=x_train.shape[1]))
"""
model.add(keras.layers.core.Dense(Y.shape[1]))
model.add(keras.layers.LeakyReLU(alpha=0.3))
model.add(keras.layers.core.Dense(Y.shape[1]))
model.add(keras.layers.LeakyReLU(alpha=0.3))
model.add(keras.layers.core.Dense(Y.shape[1]))
model.add(keras.layers.LeakyReLU(alpha=0.3))
model.add(keras.layers.core.Dense(Y.shape[1]))
model.add(keras.layers.LeakyReLU(alpha=0.3))
"""
model.add(keras.layers.core.Dense(Y.shape[1]))
model.add(keras.layers.LeakyReLU(alpha=0.3))
model.add(keras.layers.core.Dense(Y.shape[1]))
model.add(keras.layers.LeakyReLU(alpha=0.3))
model.add(keras.layers.core.Dense(Y.shape[1]))
model.add(keras.layers.LeakyReLU(alpha=0.3))
model.add(keras.layers.core.Dense(Y.shape[1]))
model.add(keras.layers.LeakyReLU(alpha=0.3))
model.add(keras.layers.core.Dense(Y.shape[1], activation='softmax'))
model.compile(loss="categorical_crossentropy", optimizer="adadelta",metrics=["accuracy"])
print(model.summary())

2023-01-15 02:03:02.079310: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-01-15 02:03:02.079324: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2023-01-15 02:03:02.079336: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Homura): /proc/driver/nvidia/version does not exist
2023-01-15 02:03:02.079468: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3528)              162288    
                                                                 
 leaky_re_lu (LeakyReLU)     (None, 3528)              0         
                                                                 
 dense_1 (Dense)             (None, 3528)              12450312  
                                                                 
 leaky_re_lu_1 (LeakyReLU)   (None, 3528)              0         
                                                                 
 dense_2 (Dense)             (None, 3528)              12450312  
                                                                 
 leaky_re_lu_2 (LeakyReLU)   (None, 3528)              0         
                                                                 
 dense_3 (Dense)             (None, 3528)              1

In [7]:
"""
model = keras.models.Sequential()
model.add(keras.Input(shape=x_train.shape[1]))

model.add(keras.layers.core.Dense(Y.shape[1], activation='sigmoid'))
model.add(keras.layers.core.Dense(Y.shape[1], activation='sigmoid'))
model.add(keras.layers.core.Dense(Y.shape[1], activation='sigmoid'))
model.add(keras.layers.core.Dense(Y.shape[1], activation='sigmoid'))
model.add(keras.layers.core.Dense(Y.shape[1], activation='sigmoid'))

model.add(keras.layers.core.Dense(Y.shape[1], activation='sigmoid'))
model.add(keras.layers.core.Dense(Y.shape[1], activation='sigmoid'))
model.add(keras.layers.core.Dense(Y.shape[1], activation='sigmoid'))
model.add(keras.layers.core.Dense(Y.shape[1], activation='softmax'))
model.compile(loss="categorical_crossentropy", optimizer="adadelta",metrics=["accuracy"])
print(model.summary())
"""

'\nmodel = keras.models.Sequential()\nmodel.add(keras.Input(shape=x_train.shape[1]))\n\nmodel.add(keras.layers.core.Dense(Y.shape[1], activation=\'sigmoid\'))\nmodel.add(keras.layers.core.Dense(Y.shape[1], activation=\'sigmoid\'))\nmodel.add(keras.layers.core.Dense(Y.shape[1], activation=\'sigmoid\'))\nmodel.add(keras.layers.core.Dense(Y.shape[1], activation=\'sigmoid\'))\nmodel.add(keras.layers.core.Dense(Y.shape[1], activation=\'sigmoid\'))\n\nmodel.add(keras.layers.core.Dense(Y.shape[1], activation=\'sigmoid\'))\nmodel.add(keras.layers.core.Dense(Y.shape[1], activation=\'sigmoid\'))\nmodel.add(keras.layers.core.Dense(Y.shape[1], activation=\'sigmoid\'))\nmodel.add(keras.layers.core.Dense(Y.shape[1], activation=\'softmax\'))\nmodel.compile(loss="categorical_crossentropy", optimizer="adadelta",metrics=["accuracy"])\nprint(model.summary())\n'

In [8]:
model.fit(x_train, y_train, batch_size=1, epochs=10, validation_data=(x_valid, y_valid), verbose=1, callbacks=[callback_early_stopping])

Epoch 1/10
5989/5989 [==============================] - 2915s 487ms/step - loss: 80.7455 - accuracy: 0.0000e+00 - val_loss: 78.5074 - val_accuracy: 0.0000e+00
Epoch 2/10
5989/5989 [==============================] - 2898s 484ms/step - loss: 102.6886 - accuracy: 0.0000e+00 - val_loss: 168.7070 - val_accuracy: 0.0000e+00
Epoch 3/10
5989/5989 [==============================] - 2882s 481ms/step - loss: 553.3632 - accuracy: 0.0000e+00 - val_loss: 1290.6359 - val_accuracy: 0.0000e+00
Epoch 4/10
5989/5989 [==============================] - 2882s 481ms/step - loss: 3557.6804 - accuracy: 0.0000e+00 - val_loss: 7205.0151 - val_accuracy: 0.0000e+00
Epoch 5/10
5989/5989 [==============================] - 2883s 481ms/step - loss: 16182.5088 - accuracy: 0.0000e+00 - val_loss: 28794.4531 - val_accuracy: 0.0000e+00
Epoch 6/10
5989/5989 [==============================] - 2877s 480ms/step - loss: 55009.1367 - accuracy: 1.6697e-04 - val_loss: 91624.3594 - val_accuracy: 8.3486e-04
Epoch 7/10
5989/5989 [===

In [9]:
character2index = jsu.read_json("10_character2index_black_clover.json")
index2character = jsu.read_json("10_index2character_black_clover.json")

In [10]:
token2index = jsu.read_json("10_token2index_black_clover.json")
index2token = jsu.read_json("10_index2token_black_clover.json")

In [20]:
hot_encoded_yuno = np.zeros((1, len(character2index)))
hot_encoded_yuno[0][character2index['Asta']] = 1

yuno = model.predict(hot_encoded_yuno)

1/1 [==============================] - 0s 34ms/step


In [21]:
top_tokens_indexes = np.argpartition(yuno[0], -100)[-100:]
top_tokens_indexes

array([1144, 1154, 1155, 1152, 1150, 1153, 1129, 1151, 1146, 1149, 1148,
       1147, 1132, 1157, 1130, 1156, 1128, 1127, 1126, 1125, 1124, 1123,
       1122, 1121, 1120, 1119, 1118, 1117, 1116, 1115, 1114, 1113, 1112,
       1111, 1110, 1109, 1108, 1107, 1106, 1105, 1207, 1208, 1158, 1159,
       1160, 1161, 1162, 1163, 3367, 1164, 1165, 1166, 1167, 1168, 1169,
       1170, 1171, 1172, 1173, 1174, 1175,  623, 1176, 1177, 1178, 3049,
       1179, 1180, 1181, 1182, 1183, 3388, 1184, 1185, 1186, 2178, 1187,
       1188, 1189, 2549, 1190, 1191, 3214, 1192, 1193, 1194, 1195, 1196,
       1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1205, 1323, 1206,
       3527])

In [22]:
for token_index in top_tokens_indexes:
    print(yuno[0][token_index], '\t', index2token[str(token_index)])

0.0 	 thrust
0.0 	 impose
0.0 	 adamantly
0.0 	 forest
0.0 	 describe
0.0 	 danger
0.0 	 relief
0.0 	 bind
0.0 	 strong
0.0 	 intent
0.0 	 regrow
0.0 	 birth
0.0 	 foot
0.0 	 enter
0.0 	 copy
0.0 	 tea
0.0 	 powerfully
0.0 	 hard
0.0 	 beaver
0.0 	 picture
0.0 	 fame
0.0 	 bike
0.0 	 behave
0.0 	 however
0.0 	 gang
0.0 	 laying
0.0 	 victory
0.0 	 banquet
0.0 	 weird
0.0 	 overhear
0.0 	 bartender
0.0 	 request
0.0 	 coincidentally
0.0 	 dimension
0.0 	 challenge
0.0 	 store
0.0 	 Orsi
0.0 	 prepared
0.0 	 cave
0.0 	 campfire
0.0 	 volatile
0.0 	 involve
0.0 	 acceptance
0.0 	 beak
0.0 	 shut
0.0 	 guard
0.0 	 knight
0.0 	 incident
7.7688645e-32 	 Asta
0.0 	 damanito
0.0 	 counter
0.0 	 result
0.0 	 afterward
0.0 	 vote
0.0 	 innocence
0.0 	 maximum
0.0 	 need
0.0 	 alive
0.0 	 busy
0.0 	 intercept
0.0 	 boys
2.6953223e-19 	 silva
0.0 	 karen
0.0 	 gamble
0.0 	 sens
2.0896612e-10 	 Noelle
0.0 	 intense
0.0 	 increase
0.0 	 alone
0.0 	 bubble
0.0 	 kahono
4.3500295e-18 	 ask
0.0 	 writi

In [14]:
np.where(yuno == np.max(yuno))

(array([0]), array([1323]))

In [15]:
index2token['1323']

'go'

In [16]:
yuno

array([[0., 0., 0., ..., 0., 0., 0.]], dtype=float32)